name: Run Bash Script Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run Bash Script
        run: ./get_available_slots.sh
        shell: bash
