name: Run Bash Script Every 5 Minutes

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '*/5 * * * *'

env:
  PARAM_COOKIE: ${{ secrets.SECRET_COOKIE }}
  PARAM_PLACE: ${{ env.VAR_PLACE }}
  PARAM_DATE: ${{ env.VAR_DATE }}
  PARAM_HOURS: ${{ env.VAR_HOURS }}

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: "Say Hello Mona it's Monday"
        run: echo "$PARAM_PLACE $First_Name. Today is $PARAM_HOURS!"
        env:
          First_Name: PLACE_2
      
      - name: Run Bash Script
        run: ./get_available_slots.sh "$PARAM_COOKIE" "$PARAM_PLACE" "$PARAM_DATE" "$PARAM_HOURS"
        shell: bash
