name: Run Bash Script Every 5 Minutes

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '*/5 * * * *'

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run Bash Script
        env:
          PARAM_COOKIE: ${{ secrets.SECRET_COOKIE }}
          PARAM_PLACE: ${{ secrets.SECRET_PLACE }}
          PARAM_DATE: ${{ secrets.SECRET_DATE }}
          PARAM_HOURS: ${{ secrets.SECRET_HOURS }}
        run: ./get_available_slots.sh "${PARAM_COOKIE}" "${PARAM_PLACE}" "${PARAM_DATE}" "${PARAM_HOURS}"
        shell: bash
